// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA20CsiHCVxySUkjExPl7ebLZdeW9RcUYo',
    appId: '1:63507132260:web:3388a0228df4f53161d471',
    messagingSenderId: '63507132260',
    projectId: 'navguide-3',
    authDomain: 'navguide-3.firebaseapp.com',
    storageBucket: 'navguide-3.appspot.com',
    measurementId: 'G-7XXKJ9K974',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWmzpvXBTmAce2vMeD5xDrA1tu0ljHy4A',
    appId: '1:63507132260:android:2aef590dc40a279461d471',
    messagingSenderId: '63507132260',
    projectId: 'navguide-3',
    storageBucket: 'navguide-3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0_cqUJvO4gpNc3eYRvXGxfqyJC2iPIYU',
    appId: '1:63507132260:ios:570b2e9edae5388d61d471',
    messagingSenderId: '63507132260',
    projectId: 'navguide-3',
    storageBucket: 'navguide-3.appspot.com',
    iosBundleId: 'com.example.navguide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0_cqUJvO4gpNc3eYRvXGxfqyJC2iPIYU',
    appId: '1:63507132260:ios:570b2e9edae5388d61d471',
    messagingSenderId: '63507132260',
    projectId: 'navguide-3',
    storageBucket: 'navguide-3.appspot.com',
    iosBundleId: 'com.example.navguide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA20CsiHCVxySUkjExPl7ebLZdeW9RcUYo',
    appId: '1:63507132260:web:6c3a8057da04cdba61d471',
    messagingSenderId: '63507132260',
    projectId: 'navguide-3',
    authDomain: 'navguide-3.firebaseapp.com',
    storageBucket: 'navguide-3.appspot.com',
    measurementId: 'G-85SFREDJ3L',
  );
}
